### ISSUE TITLE
NoMethodError: undefined method `join' with example config.rb

### ISSUE THREAD

**Issue by SLieve** [arr2036/omnigollum#27]
When I use the example config.rb with this line commented out:

    :protected_routes => ['/*'],

So that I could try it out without running my own ldap server, I get the following error:

```
Gollum::NoSuchPathError - Gollum::NoSuchPathError:
	/var/lib/gems/2.1.0/gems/gollum-grit_adapter-0.1.2/lib/grit_adapter/git_layer_grit.rb:281:in `rescue in initialize'
	/var/lib/gems/2.1.0/gems/gollum-grit_adapter-0.1.2/lib/grit_adapter/git_layer_grit.rb:276:in `initialize'
	/var/lib/gems/2.1.0/gems/gollum-lib-4.0.1/lib/gollum-lib/git_access.rb:16:in `new'
	/var/lib/gems/2.1.0/gems/gollum-lib-4.0.1/lib/gollum-lib/git_access.rb:16:in `initialize'
	/var/lib/gems/2.1.0/gems/gollum-lib-4.0.1/lib/gollum-lib/wiki.rb:227:in `new'
	/var/lib/gems/2.1.0/gems/gollum-lib-4.0.1/lib/gollum-lib/wiki.rb:227:in `initialize'
	/var/lib/gems/2.1.0/gems/gollum-3.1.1/lib/gollum/app.rb:130:in `new'
	/var/lib/gems/2.1.0/gems/gollum-3.1.1/lib/gollum/app.rb:130:in `wiki_new'
	/var/lib/gems/2.1.0/gems/gollum-3.1.1/lib/gollum/app.rb:110:in `block in <class:App>'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/var/lib/gems/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
	/var/lib/gems/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
	/var/lib/gems/2.1.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
	/var/lib/gems/2.1.0/gems/gollum-3.1.1/lib/gollum/editing_auth.rb:13:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
[2015-01-10 23:32:01] ERROR NoMethodError: undefined method `join' for #<String:0x007f93e0741b18>
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by explody** [comment]
If it helps any, I didn't get the NoSuchPathError but I did get the ```undefined method``` error. I mistakenly thought that it was a /string/ join but it was actually from a unicorn worker process trying to join, which was masking another exception that was the real error.  Check out #24 and the allow_editing issue, that fixed my particular ```join``` exception.

**Comment by SLieve** [comment]
Sorry, it's not entirely clear to me how to fix the issue. What steps did you take exactly?

**Comment by aldanor** [comment]
I am getting the same error :/ Doesn't seem to get fixed with allow_editing set to true...

**Comment by pavgup** [comment]
I ended up running into this error as well -- it was because I was inappropriately using quotes with the --h1-title option.  Dropping that option solved the problem.  We should poke at the code and make the error a bit more obvious...

**Comment by arr2036** [comment]
See https://github.com/arr2036/omnigollum/issues/24
